### ISSUE TITLE
ykman command line - same letter is used for two command line switches in oath/accounts/list

### ISSUE THREAD

**Issue by Gelmir** [Yubico/yubikey-manager#465] opened 2021-11-15 11:54 UTC
- YubiKey Manager (ykman) version: **4.0.0a1**
- How was it installed?: **apt** 
- Operating system and version: **Pop!_OS 21.04** `Linux suzy 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux`
- YubiKey model and version: **YubiKey 5 Nano (5.2.7) [OTP+FIDO+CCID] Serial: 12508567**
- Bug description summary:

Same short switches `-p` and `-p`
```
$ ykman oath accounts list -h
  -p, --period         Display the period.
  -p, --password TEXT  Provide a password to unlock the YubiKey.
```

Steps to reproduce

```
$ ykman oath accounts list -h
Usage: ykman oath accounts list [OPTIONS]

  List all credentials.

  List all credentials stored on the YubiKey.

Options:
  -H, --show-hidden    Include hidden credentials.
  -o, --oath-type      Display the OATH type.
  -p, --period         Display the period.
  -p, --password TEXT  Provide a password to unlock the YubiKey.
  -r, --remember       Remember the password on this machine.
  -h, --help           Show this message and exit.
$ ykman oath accounts list -p
Error: -p option requires an argument
ykman oath accounts list --period                                                                                                            2 ↵
MASKED:MASKED, 30
```

**Comment by dainnilsson** [comment] 2021-11-15 12:00
This is a duplicate of #427. Please update your ykman.

**Closed by dainnilsson** 2021-11-15 12:00 UTC
