### ISSUE TITLE
RFE: Need equivalent to yubico-piv-tool -a write-object

### ISSUE THREAD

**Issue by opoplawski** [Yubico/yubikey-manager#183] opened 2018-11-30 23:01 UTC
Trying to do:
```
# yubico-piv-tool -a write-object --id 0x5FC10C
Failed authentication with the application.
```
Which is apparently because yubico-piv-tool does not support the PIN derived management key on our YubiKey 4s.  ykman appears to be the successor to yubico-piv-tool, but it does not appear to have this functionality.

**Comment by dagheyman** [comment] 2018-12-03 07:40
Thanks, we'll look into adding this functionality in future versions of ykman.

In the meantime I'd recommend [contacting Yubico Support](https://support.yubico.com/support/tickets/new) for guidance on possible workarounds.

**Comment by opoplawski** [comment] 2018-12-03 16:40
Will do.  Thanks.

**Comment by smrt28** [comment] 2018-12-29 17:16
Could you please explain what does "PIN derived management key" mean? As far as I understand, you derive mgm-key from the password by hashing in some (mostly UI based) apps to make the things more user-friendly since the user doesn't have to remember "another mgm-key".

**Comment by opoplawski** [comment] 2018-12-29 23:48
> In the meantime I'd recommend [contacting Yubico Support](https://support.yubico.com/support/tickets/new) for guidance on possible workarounds.

FWIW - Yubico Support didn't have any suggestions.

**Comment by dagheyman** [comment] 2019-01-02 08:18
@smrt28 Yes, this is what YubiKey PIV Manager did, described here: https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html

In yubikey-manager however, we instead generate a random management key and store it on the device, in a slot protected by the PIN. See the command `$ ykman piv change-management-key --protect` 

The tool do support using devices setup with the old derivation scheme as well, to be compatible.

**Comment by smrt28** [comment] 2019-01-02 08:40
@dagheyman "slot protected by PIN" is something I'm looking for. I want to store an arbitrary secret on Yubikey which would be protected by the PIN and use it as a key-file for LUKS disk encryption. Could you please provide me with some details about how I can reach that? Thanks

**Comment by dagheyman** [comment] 2019-01-02 09:09
@smrt28 Look into https://web.archive.org/web/20170921144353/http://nvlpubs.nist.gov:80/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf and https://github.com/Yubico/yubikey-manager/blob/master/ykman/piv.py . We are using the slot for printed information to store the management key.

**Comment by smrt28** [comment] 2019-01-02 09:52
@dagheyman Thanks, this is interesting. It seems there are just five slots which are PIN protected. How can you be sure anybody would use the "PRINTED" slot for his own purpose and overwrite the management key without even being aware it was stored there? According to the doc, you use the slot for something which it's not supposed to be used for.

Btw, when I try to write something to the slot, I got a strange error message. Probably the piv-tool is not ready for that yet.

```
$ echo "xxxx" | yubico-piv-tool -a write-object --id=0x5fc109
Failed reading data
```

**Comment by dagheyman** [comment] 2019-01-24 11:07
read-object and write-object commands are now available on master, will be included in the next release.

**Comment by Theliel** [comment] 2019-02-08 11:46
good to know, im was waiting for this too, thank team.

**Comment by Theliel** [comment] 2019-03-13 16:09
Im tested new version, 

at least, read-object dont work in my setup (Windows 10, x64 tools and OS), work fine with old piv tool. 

ykman accept the new command, but dont retrieve the object, dont return nothing, without any error

"ykman piv read-object 0x5fc10c"

**Comment by dagheyman** [comment] 2019-03-14 07:44
@Theliel 

Could you try the command with the flags `--log-level debug` and `--log-file log.txt` ? Also, what firmware version does your YubiKey have that you are testing with?

For me this scenario works:
```
$ ykman piv write-object 0x5fc10c -
Enter a management key [blank to use default key]:
hello

$ ykman piv read-object 0x5fc10c
hello

```

**Comment by Theliel** [comment] 2019-03-14 13:55
Hi @dagheyman 

debug info give us useful information, seem to be a issue parsing/writing the Yubikey response to stdout:

YK 5 NFC, Firmware 5.1.2

1. ykman piv write-object 0x5fc10c KeyHistory.bin

Object is written correctly with c10114c20100fe00 (KeyHistory.bin content), stdout dont print nothing, but is working fine.

2. ykman piv read-object 0x5fc10c

**Object to read - 0x5fc10c**
DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00cb3fff055c03**5fc10c**'

**Response - c10114c20100fe00**
DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'5308**c10114c20100fe00**9000'
DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x000001F6A6437668>

Yubikey response correctly with the object content, but content is not parsed/printed to stdout

**Comment by opoplawski** [comment] 2019-03-14 21:36
FYI - it appears to be working fine here as well.  Thanks!

**Comment by Theliel** [comment] 2019-03-14 22:07
Curiously, work "fine" in PowerShell, the response is printed in ASCII (not hex, so binary content is a garbage, but work)

I'd tried with only ascii content too, but nothing, Windows standard shell (cmd) dont print nothing.

**Comment by dagheyman** [comment] 2019-03-15 08:07
@Theliel Yes, I can reproduce this behavior now. A workaround is to pipe the output to a file 
`$ ykman piv read-object 0x5fc10c > output.bin`, seems to work in CMD as well.

We should probably change how `read-object` prints the data, it should probably encode it somehow (as you suggest).

**Comment by leiocalyx** [comment] 2019-04-10 15:40
What is the powershell command you all use? 

I can't seem to get it to work using 
`echo C10114C20100FE00 | & 'C:\Program Files\Yubico\YubiKey Manager\ykman.exe' piv write-object 0x5fc10c -`
So far, only using this command on linux seems to work for me:
`echo -n C10114C20100FE00 | yubico-piv-tool -k -a write-object --id 0x5FC10C -i -`

**Comment by smrt28** [comment] 2019-04-10 17:15
@leiocalyx not sure if anybody in this thread uses powershel 🤔

**Comment by dainnilsson** [comment] 2021-03-03 18:24
The `ykman piv objects` subcommand in ykman 4.0 can import and export arbitrary data objects, both to/from file and stdin/stdout.

**Closed by dainnilsson** 2021-03-03 18:24 UTC
Labels: enhancement, piv
