### ISSUE TITLE
ykman oath returns "Failed connecting to the YubiKey"

### ISSUE THREAD

**Issue by ardevd** [Yubico/yubikey-manager#184] opened 2018-12-01 18:37 UTC
My YubiKey 4 has worked just fine but now will not show up in the Yubikey authenticator app and when I run ykman oath I get a "Failed connecting to YubiKey" error in return. Here is the full debug output:

This is on Fedora 29.
```
ykman --log-level DEBUG oath list
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:141] Opening driver for serial: None, pid: PID.YK4_OTP_U2F_CCID
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 1 of 10
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889ceb8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.100000 s
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 2 of 10
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cdd8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:25+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.200000 s
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 3 of 10
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cc50> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.300000 s
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 4 of 10
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cd68> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.400000 s
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 5 of 10
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889ceb8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:26+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.500000 s
2018-12-01T19:35:27+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 6 of 10
2018-12-01T19:35:27+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cdd8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:27+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:27+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.600000 s
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 7 of 10
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cc50> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.700000 s
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 8 of 10
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cd68> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:28+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.800000 s
2018-12-01T19:35:29+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 9 of 10
2018-12-01T19:35:29+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889ceb8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:29+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:29+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.900000 s
2018-12-01T19:35:30+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 10 of 10
2018-12-01T19:35:30+0100 DEBUG [ykman.descriptor.open_driver:148] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f762889cdd8> serial: 7841660, pid: PID.YK4_OTP_CCID
2018-12-01T19:35:30+0100 DEBUG [ykman.descriptor.open_driver:156] PID does not match. Want: PID.YK4_OTP_U2F_CCID, got: PID.YK4_OTP_CCID
2018-12-01T19:35:30+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 1.000000 s
2018-12-01T19:35:31+0100 DEBUG [ykman.descriptor.open_driver:163] No driver found for serial: None, pid: PID.YK4_OTP_U2F_CCID
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

**Comment by ardevd** [comment] 2018-12-01 18:39
Probably a [duplicate of this](https://github.com/Yubico/yubioath-desktop/issues/318)

**Comment by dagheyman** [comment] 2019-01-03 11:13
Thanks for the report. Agreed, it is most likely a duplicate of the issue you linked.

**Closed by dagheyman** 2019-01-03 11:13 UTC
