### ISSUE TITLE
The changelog included with PPA builds compises, 'Build for ppa'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Yubico/yubikey-manager#396] opened 2021-03-03 23:36 UTC
- YubiKey Manager (ykman) version: Irrelevant.
- How was it installed?: PPA
- Operating system and version: Linux
- YubiKey model and version: Irrelevant
- Bug description summary: no changelog for PPA build

![image](https://user-images.githubusercontent.com/47056543/109887121-1d561580-7c79-11eb-8f2d-497151c03443.png)

Steps to reproduce
---

Have PPA. Use the PPA - with `apt-listchanges` or anything else (e.g. Mint's Update Manager) that shows changelogs. 

Expected result
---

I expected to see a changelog.

Actual results and logs
---

No changelog.

Other info
---

Where on the web *are* the release notes? EDIT: ah, [I have found them](https://developers.yubico.com/yubikey-manager/Release_Notes.html). I should not have had to seek them. At least they are posted somewhere, though.

I have emailed the person whose address is listed in PPA message.

**Comment by dainnilsson** [comment] 2021-03-04 13:54
That content comes from the debian/changelog of the package, which is intended for listing changes to the package itself, not changes for the upstream package (eg. yubikey-manager).

I'm not familiar enough with Linux Mint to say if this is the "intended behavior" or not (I agree that it would probably make more sense if it showed the changelog for the actual project instead of that of the package). Can you provide more of a step-by-step account of how you got the window to appear shown in your screenshot?

**Comment by LinuxOnTheDesktop** [comment] 2021-03-04 14:08
Thanks for the reply.

'Can you provide more of a step-by-step account of how you got the window to appear shown in your screenshot?'

- Here is one option. Install `apt-listchanges` ([man page](https://www.commandlinux.com/man-page/man1/apt-listchanges.1.html)). Then set what it calls its 'frontend' to `gtk`. Then run `sudo apt update && sudo apt upgrade`.

- Alternatively: install Mint Cinnamon; add your PPA; use the Mint Update manager (you can use the web to find out how it works, but it has a GUI, and it is simple) to look for a changelog for the package. (As I said in my report, this will not show you exactly the window that I reproduced, but I think it will pull text from the same source as that window.) Or, look, probably the following will suffice: use the default graphical package manager on any spin of Debian or Ubuntu.

**Comment by LinuxOnTheDesktop** [comment] 2021-03-04 16:47
Thank you for your work.

Perhaps with apt-listchanges you need the `--confirm` option. I attach my /etc/apt/listchanges.conf (though I added a .txt extension, for GitHub).

[listchanges.conf.txt](https://github.com/Yubico/yubikey-manager/files/6085269/listchanges.conf.txt)

Are you saying all of the following? (1) In order to see the changelog (that you _do_ supply) package management software (Mint Update, apt-listchanges) need to show the 'upstream' changelog and not the 'Debian' changelog. (2) At present Mint Update - and seemingly apt-listchanges - are showing the Debian changelog.

If 1 and 2 are true, then something needs changing, such that the packaging software shores the upstream changelog. If something does need changing, then _what_ needs changing? The packaging software, or your (Yubico's) packaging?

**Comment by dainnilsson** [comment] 2021-03-04 17:12
I _think_ that's what's happening. Comparing to some other packages that had updated on my fresh Mint VM (using your apt-listchanges config worked, thanks for that!), they also seemed to show the 'Debian' changelog only. If this is the correct behavior (and I'm not missing something) then I would say it seems like a strange choice to show that changelog instead of (or in addition to) the upstream one.
While "Build for PPA" might not be the best content for that changelog either, even if we were to change it to something like "Updated upstream package to yubikey-manager 4.0.0" I still don't see that as very useful to the end user.

**Comment by LinuxOnTheDesktop** [comment] 2021-03-04 18:08
Right. Thanks. So it seems I should close this bug and file bugs against two programs. To wit: (1) apt-listchanges (if I can work out how to file a Debian bug - it is a Debian package, I think - without getting my email address plastered over the web - which is what happened last time that I tried); (2) Mint.

**Comment by dainnilsson** [comment] 2021-03-04 18:12
I have one more idea about something to try, you may want to wait for that. I believe there's a way to include both these changelogs into the package, which we may not be doing. It might be that that alters the behavior of apt-listchanges. I'm doing some experimenting around this and will post again with my results.

**Comment by dainnilsson** [comment] 2021-03-04 18:33
Ok, experimentation complete. I tested adding the upstream changelog explicitly to the build, which resulted in both files being installed under /usr/share/doc/yubikey-manager/ but apt-listchanges _still_ only shows the 'Debian' changelog, so yeah, from what I can tell showing that changelog is the intended behavior. ¯\_(ツ)_/¯

**Comment by LinuxOnTheDesktop** [comment] 2021-03-04 19:19
It occurs to me that you could put the whole 'upstream' changelog into the 'Debian' changelog. Once you've told me whether or not you are prepared to do that (or perhaps that the idea involves a misunderstanding on my part), I will close this issue.

I am in the process of trying to file a bug against apt-listchanges. I may well file one also against Mint.

**Comment by dainnilsson** [comment] 2021-03-04 19:51
I don't think putting everything in the Debian changelog is a good idea. From my understanding (and I'm happy to reconsider if that understanding is wrong) the purpose of these files is pretty clear cut: There's an "upstream" changelog for changes to the project, and there's a "Debian" changelog for changes to the packaging. Going against that doesn't seem like a good solution.

**Comment by LinuxOnTheDesktop** [comment] 2021-04-14 02:34
Please at least make the changelog easier to find. For, just now, and not for the first time, I tried, and failed, to find the changelog. Well, I did find it, but only after searching GitHub for Yubico and then relocating this issue and then making use of my own existing note on this page.

**Comment by dainnilsson** [comment] 2021-04-16 08:50
The changelog is available online here: https://developers.yubico.com/yubikey-manager/Release_Notes.html as well as here: https://github.com/Yubico/yubikey-manager/releases.
It's also included in the source release archive.
If you install the package from our PPA, then the changelog also gets installed to `/usr/share/doc/yubikey-manager/` as well (which is the standard location for Debian based systems).

I'm not sure where else to add it to make it easier to find, do you have any suggestions?

**Comment by LinuxOnTheDesktop** [comment] 2021-04-16 12:29
Thanks for the information.

I think you should add the changelog to https://www.yubico.com/ or to a subpage of that page. Or at least to somewhere that web search engines find it.

**Comment by dainnilsson** [comment] 2021-04-16 12:44
I'll forward your request to our web team!

I do think the developers.yubico.com website should be findable via search engine though. Results can vary between users, but I tried a few different search engines, searching for `yubikey manager changelog` and the correct page came up among the top hits on all of them (Google, Bing, DuckDuckGo, Yahoo).

Anyway, closing this issue again since there's nothing left _here_ to do.

**Closed by dainnilsson** 2021-04-16 12:44 UTC

**Comment by LinuxOnTheDesktop** [comment] 2021-04-16 12:49
Thanks.

There is a question about how things go when searching for the shorter and perhaps more natural string `yubikey changelog`. I find that Google does alright with that. [DuckDuckGo does less well](https://duckduckgo.com/?q=yubikey+changelog&t=ffab&ia=web).

**Comment by thompsonbrian** [comment] 2021-07-01 16:19
I can confirm that by design, apt-listchanges only shows the Debian changelog instead of adding the upstream's changelog or NEWS.  This is not to say that upstream changelogs can't be incorporated into apt-listchanges.  

See: https://www.debian.org/doc/debian-policy/ch-docs.html#s-changelogs

@LinuxOnTheDesktop I am moving the bug you filed in Debian to "wishlist" since adding upstream changelogs to either the changelog or NEWS files are left to the discretion of the Debian package maintainer.
