### ISSUE TITLE
ykman gives different code than other TOTP apps

### ISSUE THREAD

**Issue by mcarlton00** [Yubico/yubikey-manager#249] opened 2019-05-23 16:09 UTC
- YubiKey Manager (ykman) version:
```
YubiKey Manager (ykman) version: 2.1.0
Libraries:
    libykpers 1.19.3
    libusb 1.0.22
```
- How was it installed?:
Arch aur repo + pip (tried both)
- Operating system and version:
Arch linux, kernel 5.1.3

- YubiKey model and version:
```
Device type: YubiKey 5 NFC
Serial number: xxxxxxx
Firmware version: 5.1.2
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP+FIDO+CCID
NFC interface is enabled.
```
- Bug description summary:
When using any other MFA apps (andOTP, FreeOTP, google authenticator, or Yubico Authenticator, all on android), I get the same code from a given MFA source.  ykman and yubioath-desktop are giving me a different code that doesn't work.

Steps to reproduce
---
* Install yubikey-manager and yubioath-desktop
* Add MFA source (tried all 3 methods)
  * Scan QR code on screen
  * Manually enter new credentials in yubioath-desktop
  * With `ykman oath add` 
* Check MFA code against other apps with the same source

Expected result
---
To be able to log into services

Actual results and logs
---
```
% ykman --log-level DEBUG oath code
2019-05-23T12:02:42-0400 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 2.1.0
2019-05-23T12:02:42-0400 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x4, self.mode.transports: 0x7
2019-05-23T12:02:42-0400 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-05-23T12:02:42-0400 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2019-05-23T12:02:42-0400 DEBUG [ykman.descriptor.open_device:86] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x7f3daedd26d8>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2019-05-23T12:02:42-0400 DEBUG [ykman.device.__init__:198] Read config from device...
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040008a000000527471117'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'001d000000'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'2b0102023f0302023f02040094f93b04010105030501020602000007010f0801000d02023b0e02023b0a01009000'
2019-05-23T12:02:42-0400 DEBUG [ykman.device.__init__:200] Success!
2019-05-23T12:02:42-0400 DEBUG [ykman.device.__init__:290] Identified YubiKey 5
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a4040007a0000005272101'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'79030501027108a7bffcc71e9139339000'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:224] SEND: b'00a400010a7408000000000318c245'
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.send_apdu:226] RECV: b'71213150617373776f72643a7369786665657475702e3170617373776f72642e636f6d760506000f10859000'
1Password:matt  987269
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x7f3daedd26d8>
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.__del__:269] Destroy <ykman.driver_ccid.CCIDDriver object at 0x7f3daedd26d8>
2019-05-23T12:02:42-0400 DEBUG [ykman.driver_ccid.close:265] Close <ykman.driver_ccid.CCIDDriver object at 0x7f3daedd26d8>
```
Code is different than what is received in other apps, and doesn't work when attempting to log in

Other info
---

Plugging the same yubikey (that was programmed on my Arch machine) into a Ubuntu 18.04 machine gives me the correct codes.

All indicators are pointing to something weird on my local machine, but I haven't found where to start looking for it

**Comment by dagheyman** [comment] 2019-05-24 09:31
> All indicators are pointing to something weird on my local machine, but I haven't found where to start looking for it

Firs thing to check is the system clock, since the current time is used to generate the TOTP code. 

Also feel free to contact [Yubico Support ](https://support.yubico.com/support/tickets/new), they might be able to help out. Closing this issue since it's not something reproducible with the software.

**Closed by dagheyman** 2019-05-24 09:31 UTC
