### ISSUE TITLE
User prompted to touch YK even with touch-policy = NEVER

### ISSUE THREAD

**Issue by jursed** [Yubico/yubikey-manager#345] opened 2020-06-02 16:08 UTC
- YubiKey Manager (ykman) version: 3.1.1
- Library versions: libykpers 1.20.0, libusb 1.0.21
- How was it installed?: [Yubico PPA](http://ppa.launchpad.net/yubico/stable/ubuntu/) 
- Operating system and version: Ubuntu 18.04.4, Linux 5.3.0-45
- YubiKey model and version: YubiKey 5 NFC, firmware 5.1.2
- Bug description summary:

Ykman prompts the user to touch the Yubikey upon importing of certificate, even if the touch policy for the corresponding private key (generated on-device) has been set to **never** (i.e. `ykman piv generate-key --touch-policy NEVER`)

After this prompt, the user is still allowed to enter the PIN (as per the policy), and the result is OK. However, it makes for a very confusing UI.

Steps to reproduce
---

- `ykman config usb --enable PIV` (and `--disable` all other modes, if enabled)
- `ykman piv generate-key --algorithm RSA2048 --pin-policy ALWAYS --touch-policy NEVER 9a test_key.pub`
- `ykman piv generate-csr --subject "test" 9a test_key.pub test_csr.req`
- Obtain the certificate
- `ykman piv import-certificate --verify 9a test_cert.crt`

Upon executing this last step, ykman prints this

```
Enter a management key [blank to use default key]: 
```

...and then, after entering the correct management key, it prints exactly this (including the trailing newline):

```
Enter PIN: Touch your YubiKey...

````

At this point, the program waits for the user's input (PIN). If the correct one is submitted, the operation succeds. If the user tries touching the YK, the operation fails.

Expected result
---

Upon executing the last step, i.e. `ykman piv import-certificate --verify 9a test_cert.crt`, I expect to be prompted **only** for the PIN, and **not** to touch the YK. It's a minor UI bug, but it cost me a long time (and several iterations of obtaining an entirely new private key and certificate) to figure it out. :)

**Comment by dagheyman** [comment] 2020-06-03 05:54
Thanks for the report!
Can you reproduce this reliably?
I went through the steps but I only get prompted for the PIN as expected.

**Comment by dagheyman** [comment] 2020-06-03 06:00
Looking [at the code](https://github.com/Yubico/yubikey-manager/blob/255485c19ef291e055bdb8a192c86d01f67e1929/ykman/piv.py#L888) however, I can see how this can happen if the signing operation takes more than 0.5 seconds. The underlaying problem is that there is no way to read out the touch policy of the key, so we assume touch is required if no response is coming back. Apparently not the most reliable design.

**Comment by jursed** [comment] 2020-06-03 17:33
Thanks for the quick response!

> Can you reproduce this reliably?

Yes, as far as I can tell, this bug does appear every time I do this.

> I can see how this can happen if the signing operation takes more than 0.5 seconds

I can corroborate that `Enter PIN:` appears (instantly) first and `Touch your YubiKey...\n` appears after a short delay (which could very well be the 0.5s).

It's not a huge deal, because as far as I can tell, the import operation works correctly. As a quick fix, I would propose sth like:
* Eliminate the second "Touch your Yubikey" prompt
* Modify the first "Enter PIN" prompt (explaining that YK *might* need to be touched according to the previously set policy)

(Just a thought.)

**Comment by dainnilsson** [comment] 2021-04-16 06:53
It looks like we were never able to reproduce this. A lot of the code handling this was reworked for 4.0, so there's a good chance it now works. I'm closing this issue now, but if the problem is still present in ykman 4.0 please feel free to reopen it!

**Closed by dainnilsson** 2021-04-16 06:53 UTC
